#if !canImport(ObjectiveC)
import XCTest

extension KoreanigaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KoreanigaTests = [
        ("testSydneyOperaHouse", testSydneyOperaHouse),
        ("testTibetanSandFox", testTibetanSandFox),
        ("testUDHR1", testUDHR1),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KoreanigaTests.__allTests__KoreanigaTests),
    ]
}
#endif
